### ISSUE TITLE
src/PaymentServiceProvider.php hardcoded to Europabank gateway?

### ISSUE THREAD

**Issue by berijan** [spatie/payment#10]
Hi.

I searching for a solution to implement a checkout gateway for my business and found Your sample which seems to suits my needs. I new to Laravel but have started to learning so I'm not so into it yet.

However i have a question about payment/src/PaymentServiceProvider.php.
When first looking in to spatie/payment I thought all code was generic except for ./Gateways/Europabank/ so I planned to make one implementation like ./Gateways/MyBankGateway. 

But then when looking in ./src/PaymentServiceProvider.php I found Europabank hardcoded into that file, in,
- row 6 "use Spatie\Payment\Gateways\Europabank\PaymentGateway as EuropabankPaymentGateway;"
- row 27, "$this->app->bind(PaymentGateway::class, EuropabankPaymentGateway::class);"

If that hard coding needs to be there shouldn't the ./src/PaymentServiceProvider be located in the ./Gateways/Europabank/ folder since it a Eurobank specific files.

Or can the  ./src/PaymentServiceProvider.php be made generic and having the real gateway as a "parameter" in some way?

Regards
Jan Bulér

**Comment by freekmurze** [comment]
Hi,

we currently are not supporting this package anymore. I'll make a note of this in the readme. 

Feel free to fork the code and adapt it to your own needs.
